name: project_t_ping
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  fl_chart: ^0.69.0
  quickalert: ^1.1.0
  syncfusion_flutter_charts: ^27.1.51
  flutter_launcher_icons: ^0.13.1
  another_flutter_splash_screen: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/Image/Icon/icon2.png"

flutter:
  assets:
    - assets/Image/BG/
    - assets/Image/index/
    - assets/Image/Logo/SciLogo.png

  uses-material-design: true
